FLSTKBACK-8
simpleqteam/flystalker-backend pull request #7
Opened 2020-04-15 15:29 UTC by Vladf8

2020-04-16 11:59 UTC, sttimort requested changes

2020-04-16 11:59 UTC, sttimort commented on src/main/kotlin/xyz/simpleq/flystalker/controller/ExchangesController.kt
> +    fun getPageByPageInfo(@PathVariable skip: Int, @PathVariable take: Int) =
Давай обзовем url `/search` и вынесем `skip` и `take` в query-параметры
И метод тогда тоже в `search`

2020-04-16 11:59 UTC, sttimort commented on src/main/kotlin/xyz/simpleq/flystalker/service/impl/ExchangesStateManagerImpl.kt
> +                        throw IllegalArgumentException("Error: argument take must be greater than 0 ")
Валидацию стоит вынести из defer в отдельный метод, типа такого:
```kotlin
private fun validateSearchRequest(request: SearchRequest): Mono<Void> = when {
    request.take < 1 -> Mono.error(IllegalArgumentException("..."))
    else -> Mono.empty()
}
```

2020-04-16 11:59 UTC, sttimort commented on src/main/kotlin/xyz/simpleq/flystalker/service/impl/ExchangesStateManagerImpl.kt
> +                    }
А есть вариант сделать это одним запросом?
Может если разделить skip / take, получим кол-во страниц, которые нужно пропустить и take тогда можно взять в качестве размера одной страницы

2020-04-16 16:35 UTC, Vladf8 commented on src/main/kotlin/xyz/simpleq/flystalker/service/impl/ExchangesStateManagerImpl.kt
> +                    }
Переделаю метод на стандартные параметры pageNumber и pageSize

2020-04-19 12:09 UTC, sttimort approved these changes

2020-04-19 13:15 UTC, merged